image: python:latest

services:
  - mysql:5.7

variables:
  MYSQL_ROOT_PASSWORD: gkjfsda875afsd87
  MYSQL_DATABASE: backend
  DJANGO_SETTINGS_MODULE: settings.development

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - pip install -r requirements-production.txt
  - python manage.py migrate

test:
  script:
    - python manage.py test
