image: python:latest

services:
  - mysql:latest

variables:
  MYSQL_ROOT_PASSWORD: akkaskhooneh
  MYSQL_DATABASE: backend
  MYSQL_USER: akkaskhooneh
  MYSQL_PASSWORD: akkaskhooneh

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - pip install -r requirements-productions.txt

test:
  variables:
    DJANGO_SETTINGS_MODULE: settings.ci
  script:
    - python manage.py test
