image: python:latest

services:
  - mysql:5.7

variables:
  MYSQL_ROOT_PASSWORD: gkjfsda875afsd87
  MYSQL_DATABASE: backend

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - pip install -r requirements-production.txt

test:
  variables:
    DJANGO_SETTINGS_MODULE: settings.ci
  before_script:
    - python manage.py migrate
  script:
    - python manage.py test
