language: python

python:
  - "3.6"

services:
  - redis-server

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=social,authentication manage.py test

after_success:
  - coveralls
