lang: python

python:
  - "3.7"

services:
  - redis-server

before_install:
  - python --version
  - pip install --upgrade pip

install:
  - pip install --user -r requirements.txt
  - python manage.py migrate

script:
  - python manage.py test
