lang: python

python:
  - "3.6"

services:
  - redis-server

before_install:
  - python3 --version
  - pip3 install --upgrade pip

install:
  - pip3 install --user -r requirements.txt
  - python manage.py migrate

script:
  - python manage.py test
