# Generated by Django 2.1 on 2018-08-21 12:19

import authentication.managers.user_manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentication.managers.user_manager.UserManager()),
            ],
        ),
    ]
