# Generated by Django 2.1 on 2018-09-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_notification_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
