# Generated by Django 2.1 on 2018-09-05 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
