# Generated by Django 2.1 on 2018-09-05 12:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0005_request_request_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'post', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('user', 'following')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('requester', 'requestee')},
        ),
        migrations.AlterUniqueTogether(
            name='tagcontains',
            unique_together={('tag', 'post')},
        ),
    ]
